{-# language CPP #-}
module Linear.SUM3 where

#define INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,DD) \
INST_LINEAR2(AA,BB,(# CC | DD | () #)); \
INST_LINEAR2(AA,BB,(# CC | DD | A# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | I #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Int8# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Int16# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Int32# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Int64# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | U #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Word8# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Word16# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Word32# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | Word64# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | P# #)); \
INST_LINEAR2(AA,BB,(# CC | DD | F32 #)); \
INST_LINEAR2(AA,BB,(# CC | DD | F64 #))

#define INSTS_SUM2_CC_LINEAR2(AA,BB,CC) \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,()); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,A#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,I); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Int8#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Int16#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Int32#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Int64#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,U); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Word8#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Word16#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Word32#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,Word64#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,P#); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,F32); \
INSTS_SUM_CC_DD_LINEAR2(AA,BB,CC,F64)

#define INSTS_SUM2_LINEAR2(AA,BB) \
INSTS_SUM2_CC_LINEAR2(AA,BB,()); \
INSTS_SUM2_CC_LINEAR2(AA,BB,A#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,I); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Int8#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Int16#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Int32#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Int64#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,U); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Word8#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Word16#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Word32#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,Word64#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,P#); \
INSTS_SUM2_CC_LINEAR2(AA,BB,F32); \
INSTS_SUM2_CC_LINEAR2(AA,BB,F64)

