name: prim
github: daig/prim
version: 0.7.0.0
category: Prelude
synopsis: A modern interface to ghc-prim
description: This library reorganizes @ghc-prim@
             For usability and documentation of
             low-level programming.
stability: cursed
author: Dai
maintainer: dai@sodality.cc
copyright: 2021 Sodality
license: MIT
verbatim:
  cabal-version: 3.4

default-extensions:
  - MagicHash
  - FunctionalDependencies
  - ScopedTypeVariables
  - UnboxedTuples
  - KindSignatures
  - PolyKinds
  - ConstraintKinds
  - TypeOperators
  - RankNTypes
  - BlockArguments
  - UnicodeSyntax
  - PatternSynonyms
  - ViewPatterns
  - DataKinds
  - UnliftedNewtypes
  - GADTs
  - TypeSynonymInstances
  - TypeFamilies
  - DerivingStrategies
  - StandaloneDeriving
  - GeneralizedNewtypeDeriving
  - FlexibleInstances
  - MultiParamTypeClasses
  - AllowAmbiguousTypes
  - TypeFamilyDependencies
  - PostfixOperators
  - TypeApplications
  - FlexibleContexts
  - LambdaCase
  - LexicalNegation
  - TupleSections
  - NumericUnderscores
  - BinaryLiterals
  - HexFloatLiterals
  - StandaloneKindSignatures
  - QualifiedDo
  - DerivingVia

library:
  source-dirs: src
  other-modules: Prelude
  dependencies:
    - microbase
    - prim:ffi
    - prim:string
    - prim:type
    - prim:stock
    - prim:class
    - ghc-prim

internal-libraries:
  type:
    source-dirs: type
    other-modules: []
    dependencies: ghc-prim
  do:
    source-dirs: do
    other-modules: Prelude
    default-extensions:
      - CPP
    dependencies:
      - prim:type
      - ghc-prim
      - microbase
  class:
    source-dirs: class
    other-modules: Prelude
    dependencies:
      - ghc-prim
      - prim:type
      - prim:ffi
      - prim:do
      - microbase
  stock:
    source-dirs: stock
    other-modules: Prelude
    visibility: public
    dependencies:
      - microbase
      - ghc-prim
  string:
    other-modules: Prelude
    source-dirs: string
    visibility: public
    dependencies: ghc-prim
  ffi:
    other-modules: []
    source-dirs: ffi
    visibility: public
    includes: ffi/cbits/primitive-memops.h
    c-sources: ffi/cbits/primitive-memops.c
    dependencies: ghc-prim
  thread:
    other-modules: []
    source-dirs: thread
    visibility: public
    dependencies:
      - prim:type
      - prim:class
